### ISSUE TITLE
Admin dashboard or any other screen not loading

### ISSUE THREAD

**Issue by Elamurugan-Nallathambi** [magespices/mage2nostalgia#1]
### Preconditions
Installed and activated theme, ran setup/deploy and everything worked out ok including login screen

Magento Version:2.3.3 Commerce edition

Environment: EC2 Ubuntu instance

Third party modules: None, default Magento

### Steps to reproduce

1. As soon as login endup seeing the below exception

### Expected result

1. Actual admin screens

### Actual result

var/report/1004248632942
`{"0":"Missing required param title","1":"<pre>#1 Magento\\Backend\\Model\\Menu\\Item\\Validator->validate() called at [vendor\/magento\/module-backend\/Model\/Menu\/Item.php:180]\n#2 Magento\\Backend\\Model\\Menu\\Item->__construct() called at [generated\/code\/Magento\/Backend\/Model\/Menu\/Item\/Interceptor.php:14]\n#3 Magento\\Backend\\Model\\Menu\\Item\\Interceptor->__construct() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/AbstractFactory.php:116]\n#4 Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->createObject() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Dynamic\/Developer.php:66]\n#5 Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create() called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:56]\n#6 Magento\\Framework\\ObjectManager\\ObjectManager->create() called at [vendor\/magento\/module-backend\/Model\/Menu\/Item\/Factory.php:35]\n#7 Magento\\Backend\\Model\\Menu\\Item\\Factory->create() called at [vendor\/magento\/module-backend\/Model\/Menu\/Builder.php:66]\n#8 Magento\\Backend\\Model\\Menu\\Builder->getResult() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#9 Magento\\Backend\\Model\\Menu\\Builder\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#10 Magento\\Backend\\Model\\Menu\\Builder\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#11 Magento\\Backend\\Model\\Menu\\Builder\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Backend\/Model\/Menu\/Builder\/Interceptor.php:39]\n#12 Magento\\Backend\\Model\\Menu\\Builder\\Interceptor->getResult() called at [vendor\/magento\/module-backend\/Model\/Menu\/Config.php:148]\n#13 Magento\\Backend\\Model\\Menu\\Config->_initMenu() called at [vendor\/magento\/module-backend\/Model\/Menu\/Config.php:111]\n#14 Magento\\Backend\\Model\\Menu\\Config->getMenu() called at [vendor\/magento\/module-backend\/Model\/Url.php:365]\n#15 Magento\\Backend\\Model\\Url->_getMenu() called at [vendor\/magento\/module-backend\/Model\/Url.php:325]\n#16 Magento\\Backend\\Model\\Url->getStartupPageUrl() called at [vendor\/magento\/module-backend\/Controller\/Adminhtml\/Index\/Index.php:24]\n#17 Magento\\Backend\\Controller\\Adminhtml\\Index\\Index->execute() called at [generated\/code\/Magento\/Backend\/Controller\/Adminhtml\/Index\/Index\/Interceptor.php:24]\n#18 Magento\\Backend\\Controller\\Adminhtml\\Index\\Index\\Interceptor->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:108]\n#19 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/module-backend\/App\/AbstractAction.php:231]\n#20 Magento\\Backend\\App\\AbstractAction->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#21 Magento\\Backend\\Controller\\Adminhtml\\Index\\Index\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#22 Magento\\Backend\\Controller\\Adminhtml\\Index\\Index\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php:143]\n#23 Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#24 Magento\\Backend\\Controller\\Adminhtml\\Index\\Index\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#25 Magento\\Backend\\Controller\\Adminhtml\\Index\\Index\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Backend\/Controller\/Adminhtml\/Index\/Index\/Interceptor.php:39]\n#26 Magento\\Backend\\Controller\\Adminhtml\\Index\\Index\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:159]\n#27 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:99]\n#28 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#29 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#30 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#31 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n#32 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:137]\n#33 Magento\\Framework\\App\\Http->launch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#34 Magento\\Framework\\App\\Http\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#35 Magento\\Framework\\App\\Http\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#36 Magento\\Framework\\App\\Http\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:26]\n#37 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:261]\n#38 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:43]\n<\/pre>","url":"\/backend\/admin\/","script_name":"\/index.php"}`

**Comment by jakwinkler** [comment]
Nostalgia theme has been only tested on OpenSource version. 
However are welcome to submit a pull request regarding Commerce Edition @Elamurugan-Nallathambi 
Closing the issue.
